export default {
  health_up: ['Health Up', 'أصحاء'],
  registration_successful: ['Registration successful', 'تم التسجيل '],
  login_successful: ['Login successful', 'تم تسجيل الدخول بنجاح'],
  invalid_login_credentials: ['Invalid login credentials', 'معلومات الدخول غير صحيحة'],
  email_used: ['The email you provided is already in use'],
  company: ['Company', 'المنشأة'],
  ambulance_man: ['Ambulance Man', 'المسعف'],
  admin: ['Admin', 'المشرف'],
  normal_user: ['Normal', 'فرد'],
  user_does_not_exist: ['User with this email does not exist', 'لايوجد حساب مسجل بهذا البريد '],
  ambulance_does_not_exist: ['Ambulance with this email or id does not exist', 'لايوجد مسعف مسجل بهذا البريد او الهوية '],
  password_updated: ['Password updated successfully', 'تم تحديث كلمة المرور'],
  successful: ['Successful', 'نجح'],
  not_found: ['Not found'],
  account_not_verified: ['Your account has not been verified. Please contact the administrator.', 'لم يتم تفعيل حسابك يرجى التواصل مع الدعم الفني '],
  notification_created: ['Notification has been created successfully', 'تم انشى التنبيه'],
  notification_updated: ['Notification has been updated successfully', 'تم تحديث التنبيه'],
  notification_deleted_successfully: ['Notification deleted successfully', 'تم حذف التنبيه'],
  greeting: ['Hello, {}', 'مرحبا, {}'],
  health_alert: ['Health Alert', 'تنبيه صحي'],
  id_number_exists: ['A user with this id number already exists']
};
